title: "Zawad's Cybersecurity Blog"
description: "Learning cybersecurity one step at a time – TryHackMe, SOC, Splunk, and more."
baseurl: "/simanta-cyber-dev.github.io"
url: "https://simanta2330.github.io"
theme: minimal-mistakes-jekyll

author:
  name: Zawad
  bio: "Cybersecurity Learner | SOC Enthusiast | 2nd Year CSE Student"
  location: "Bangladesh"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
